from typing import Protocol, runtime_checkable
from phitest.domain.models import (
    Subject, Experiment, Run, Stimulus, Observation,
    Intervention, MetricResult, EvidenceClaim, AuditEvent,
)


@runtime_checkable
class Repository(Protocol):
    # Subjects
    def save_subject(self, subject: Subject) -> None: ...
    def get_subject(self, subject_id: str) -> Subject | None: ...
    def list_subjects(self) -> list[Subject]: ...

    # Experiments
    def save_experiment(self, experiment: Experiment) -> None: ...
    def get_experiment(self, experiment_id: str) -> Experiment | None: ...
    def list_experiments(self, subject_id: str | None = None) -> list[Experiment]: ...
    def update_experiment_status(self, experiment_id: str, status: str) -> None: ...

    # Runs
    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, experiment_id: str | None = None) -> list[Run]: ...
    def update_run(self, run: Run) -> None: ...

    # Stimuli
    def save_stimulus(self, stimulus: Stimulus) -> None: ...
    def list_stimuli(self, run_id: str) -> list[Stimulus]: ...

    # Observations
    def save_observation(self, observation: Observation) -> None: ...
    def list_observations(self, run_id: str) -> list[Observation]: ...

    # Interventions
    def save_intervention(self, intervention: Intervention) -> None: ...
    def list_interventions(self, run_id: str) -> list[Intervention]: ...

    # Metrics
    def save_metric_result(self, metric: MetricResult) -> None: ...
    def list_metric_results(self, run_id: str) -> list[MetricResult]: ...

    # Claims
    def save_evidence_claim(self, claim: EvidenceClaim) -> None: ...
    def list_evidence_claims(self, run_id: str) -> list[EvidenceClaim]: ...

    # Audit
    def append_audit_event(self, event: AuditEvent) -> None: ...
    def list_audit_events(self) -> list[AuditEvent]: ...
    def get_last_audit_event(self) -> AuditEvent | None: ...

    # Health
    def schema_version(self) -> int: ...
